services:
  - type: web
    name: it-support-backend
    env: node
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: "20"
